controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
app_default:
  path: "/"
  controller: 'App\Controller\IndexController::index'
admin_user_list:
    path: /admin/users
    controller: App\Controller\AdminController::listUsers